#!/bin/bash
# Copyright (c) 2022 Innodisk crop.
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

MODE=${1}
PLATFORM=${2:-"arm"}
LIBTYPE=${3:-"static"}
LIBAUG=""
if [ "$LIBTYPE" == "shared" ] ; then
    LIBAUG="${LIBAUG} -DSHAREDLIB=ON"
fi
if [ "$PLATFORM" == "arm" ] ; then
    LIBAUG="${LIBAUG} -DCROSSCOMPILE=ON"
fi

case ${MODE} in
    build)
        cmake $LIBAUG -H. -Bbuild_${PLATFORM}
        cd ./build_${PLATFORM}
        make
        cp ./stesting ../
        cd ../
    ;;
    clean)
        rm -rf ./build*
        rm -rf ./stesting
        rm -rf ./log.json
    ;;
    *)  
        echo "${0} <MODE> <PLATFORM> <LIBTYPE>"
        echo "    MODE:"
        echo "        build, release, clean"
        echo "    PLATFORM:"
        echo "        host, arm(default)"
        echo "    LIBTYPE:"
        echo "        shared, static(default)"
    ;;
esac
